import Axios from "axios";
import './util/axiosConfig';
import './util/extend';
import './filter';
import './directive';
import httpIntercept from "./util/httpIntercept";
import cacheWraperAxios from "./util/extendAxios";
import { config } from "./util/wxconfig";
httpIntercept(Axios);
cacheWraperAxios(Axios);
config();