export default {
  GET_USER: "GET_USER",
  UPDATE_USER: "UPDATE_USER",
  SET_BASE_DATA:"SET_BASE_DATA",
  UPDATE_PRICES:"UPDATE_PRICES",
  UPDATE_BASEINFO:"UPDATE_BASEINFO",
  UPDATE_OTHER:"UPDATE_OTHER"
};
